spring:
  sql:
    init:
      encoding: utf-8
  jpa:
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
roomescape:
  auth:
    cookie:
      name: token
