spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:database
    driver-class-name: org.h2.Driver
  jpa:
    ddl-auto: create-drop
    defer-datasource-initialization: true
roomescape:
  auth:
    jwt:
      secret: Yn2kjibddFAWtnPJ2AFlL8WXmohJMCvigQggaEypa5E=
      expiration: 300000
