spring:
  profiles:
    active: prod
  h2:
    console:
      enabled: false
  datasource:
    url: jdbc:h2:mem:database
    driver-class-name: org.h2.Driver
  jpa:
    ddl-auto: update
    defer-datasource-initialization: false
roomescape:
  auth:
    jwt:
      secret: Yn2kjibddFAWtnPJ2AFlL8WXmohJMCvigQggaEypa5E=
      expiration: 3600000
